# render.yaml - Infrastructure as Code for Render
services:
  - type: web
    name: escrowflow-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8125885886:AAF1Q4MiOHNiTSo2BhjEmnUiQ39yAtGzDYs"
    plan: free
    autoDeploy: true
    region: oregon
