# render.yaml
services:
  - type: web
    name: escrowflow-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python escrowflow_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8125885886:AAF1Q4MiOHNiTSo2BhjEmnUiQ39yAtGzDYs
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    branch: main
    healthCheckPath: /health
