services:
  - type: web
    name: escrowflow-bot
    runtime: python
    buildCommand: |
  python -m pip install --upgrade pip
  pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 app:application
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8125885886:AAF1Q4MiOHNiTSo2BhjEmnUiQ39yAtGzDYs"
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /health

# Health check endpoint (add to app.py)
@app.route('/health')
def health():
    return jsonify({"status": "healthy"}), 200
